// demos/toolkit/solid/src/components/DemoToolbar.tsx
/****************************************************************************
 ** @license
 ** This demo file is part of yFiles for HTML.
 ** Copyright (c) 2026 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ** yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 **
 ** Owners of a valid software license for a yFiles for HTML version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles for HTML powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles for HTML
 ** license agreement.
 **
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 ***************************************************************************/
import { Command, GraphComponent } from '@yfiles/yfiles'
import { onMount } from 'solid-js'

type DemoToolbarProps = {
  graphComponent: () => GraphComponent
  resetGraph: () => void
  layout: () => void
}
export const DemoToolbar = (props: DemoToolbarProps) => {
  const commandCallbacks = {
    resetData: () => {},
    zoomIn: () => {},
    resetZoom: () => {},
    zoomOut: () => {},
    fitContent: () => {}
  }

  onMount(() => {
    const graphComponent = props.graphComponent()
    commandCallbacks.resetData = () => props.resetGraph()
    commandCallbacks.zoomIn = () => graphComponent.executeCommand(Command.INCREASE_ZOOM)
    commandCallbacks.zoomOut = () => graphComponent.executeCommand(Command.DECREASE_ZOOM)
    commandCallbacks.resetZoom = () => graphComponent.executeCommand(Command.ZOOM, 1.0)
    commandCallbacks.fitContent = () => void graphComponent.fitGraphBounds()
  })

  return (
    <div class="component-toolbar">
      <button title="Zoom In" onClick={() => commandCallbacks.zoomIn()}>
        <span class="material-symbols-outlined">zoom_in</span>
      </button>
      <button title="Zoom Out" onClick={() => commandCallbacks.zoomOut()}>
        <span class="material-symbols-outlined">zoom_out</span>
      </button>
      <button title="Fit Diagram" onClick={() => commandCallbacks.fitContent()}>
        <span class="material-symbols-outlined">zoom_out_map</span>
      </button>
      <span class="separator"></span>
      <button class="labeled" onClick={() => props.layout()}>
        <span class="material-symbols-outlined">play_arrow</span>Layout
      </button>
      <span class="separator"></span>
      <button title="Reset Graph" onClick={() => commandCallbacks.resetData()}>
        <span class="material-symbols-outlined">refresh</span>
      </button>
    </div>
  )
}

// demos/toolkit/next/app/components/DemoToolbar.tsx
/****************************************************************************
 ** @license
 ** This demo file is part of yFiles for HTML.
 ** Copyright (c) 2026 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ** yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 **
 ** Owners of a valid software license for a yFiles for HTML version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles for HTML powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles for HTML
 ** license agreement.
 **
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 ***************************************************************************/
import React, { ChangeEvent } from 'react'

interface DemoToolbarProps {
  resetData(): void
  resetZoom(): void
  fitContent(): void
  zoomIn(): void
  zoomOut(): void
  searchChange(e: ChangeEvent<HTMLInputElement>): void
}

export default function DemoToolbar(props: DemoToolbarProps) {
  return (
    <div className="component-toolbar">
      <button title="Reset Data" onClick={props.resetData}>
        <span className="material-symbols-outlined">refresh</span>
      </button>
      <span className="separator" />
      <button title="Zoom Out" onClick={props.zoomOut}>
        <span className="material-symbols-outlined">zoom_out</span>
      </button>
      <button title="Zoom In" onClick={props.zoomIn}>
        <span className="material-symbols-outlined">zoom_in</span>
      </button>
      <button title="Fit Diagram" onClick={props.fitContent}>
        <span className="material-symbols-outlined">zoom_out_map</span>
      </button>
      <span className="separator" />
      <label>
        Search:
        <input className="search" onChange={props.searchChange} />
      </label>
    </div>
  )
}
