// demos/toolkit/react-class-components/src/App.tsx
/****************************************************************************
 ** @license
 ** This demo file is part of yFiles for HTML.
 ** Copyright (c) 2026 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ** yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 **
 ** Owners of a valid software license for a yFiles for HTML version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles for HTML powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles for HTML
 ** license agreement.
 **
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 ***************************************************************************/
import { Component } from 'react'
import './App.css'
import ReactGraphComponent from './components/ReactGraphComponent'
import DemoDescription from './components/DemoDescription'

export default class App extends Component {
  render() {
    return (
      <>
        <div className="demo-header">
          <a
            href="https://www.yfiles.com/the-yfiles-sdk/web/yfiles-for-html"
            className="y-logo"
            target="_blank"
            title="yFiles Product Page"
          ></a>
          <span className="material-symbols-outlined">chevron_right</span>
          <a
            href="https://www.yfiles.com/demos"
            className="breadcrumb-wrapper"
            target="_blank"
            rel="noopener noreferrer"
          >
            Demos
          </a>
          <span className="material-symbols-outlined">chevron_right</span>
          <span id="name" className="breadcrumb-wrapper demo-name">
            React Class Components
          </span>
        </div>
        <div className="demo-main">
          <ReactGraphComponent />
          <div className="demo-main__description-panel">
            <DemoDescription />
          </div>
        </div>
      </>
    )
  }
}

// demos/toolkit/solid/src/App.tsx
/****************************************************************************
 ** @license
 ** This demo file is part of yFiles for HTML.
 ** Copyright (c) 2026 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ** yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 **
 ** Owners of a valid software license for a yFiles for HTML version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles for HTML powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles for HTML
 ** license agreement.
 **
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 ***************************************************************************/
import type { Component } from 'solid-js'
import './App.css'
import { SolidGraphComponent } from './components/SolidGraphComponent'
import { DemoDescription } from './components/DemoDescription'

export const App: Component = () => {
  return (
    <>
      <div class="demo-header">
        <a
          href="https://www.yfiles.com/the-yfiles-sdk/web/yfiles-for-html"
          class="y-logo"
          target="_blank"
          title="yFiles Product Page"
        ></a>
        <span class="material-symbols-outlined">chevron_right</span>
        <a
          href="https://www.yfiles.com/demos"
          class="breadcrumb-wrapper"
          target="_blank"
          rel="noopener noreferrer"
        >
          Demos
        </a>
        <span class="material-symbols-outlined">chevron_right</span>
        <span id="name" class="breadcrumb-wrapper demo-name">
          SolidJS Demo
        </span>
      </div>
      <div class="demo-main">
        <SolidGraphComponent />
        <div class="demo-main__description-panel">
          <DemoDescription />
        </div>
      </div>
    </>
  )
}

export default App
